---
# This is not a work of art, but out of necessity. I know this can be made much nicer

- name: Import Spotlight maintenance tasks
  ansible.builtin.import_tasks: spotlight.yml

# repair permissions
# figure out current user id
- name: Find user id / $(id -u)
  ansible.builtin.command: id -u
  register: maintenance_userid
  tags: maintenance

# warning: this command can not be canceled. Runtime is ca. 2 mins for 500gb
- name: Run 'diskutil resetuserpermissions / $(id -u)'
  ansible.builtin.command: "diskutil resetuserpermissions / {{ maintenance_userid.stdout }}"
  become: true
  tags: maintenance

# Check disk
# Get list with 'diskutil list'
- name: Run 'diskutil verifyVolume /dev/disk1'
  ansible.builtin.command: "diskutil verifyVolume /dev/disk1"
  become: true
  tags: maintenance

# flush DNS
- name: Run 'dscacheutil -flushcache && killall -HUP mDNSResponder'
  ansible.builtin.command: "dscacheutil -flushcache && killall -HUP mDNSResponder"
  become: true
  tags: maintenance

# empty all Trashes
- name: Run 'rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash;'
  ansible.builtin.command: "rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash;"
  become: true
  tags: maintenance, skip_ansible_lint

# Speed up terminal by clearing ASL logs
- name: Run 'rm -rfv /private/var/log/asl/*.asl'
  ansible.builtin.file:
    path: '/private/var/log/asl/*.asl'
    state: absent
  become: true
  tags: maintenance

# Delete launch service quarantine (list of all files ever downloaded)
- name: Clean up LaunchServices quarantine
  ansible.builtin.command: "bash {{ ansible_user_dir }}/Code/private/dotfiles/bin/clean_osx_downloads.sh"
  tags: maintenance

# Reset LaunchServices db
# Splitting this into 2 lines to stay under our line limit of 180 chars
- name: Clean up LaunchServices to remove duplicates in the “Open With” menu
  ansible.builtin.command: >
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister
    -kill -r -domain local -domain system -domain user && killall Finder
  become: true
  tags: maintenance

# Purge memory
- name: Purge inactive memory
  ansible.builtin.command: sudo purge
  become: true
  tags: maintenance

# Run periodics
- name: Run periodic scripts
  ansible.builtin.command: sudo periodic daily weekly monthly
  become: true
  tags: maintenance

# - name: Delete all .DS_Store files
#   ansible.builtin.command: find ~/ -name ".DS_Store" -exec rm {} \;
#   become: true
#   tags: maintenance

# Run rm -rf ~/Library/Caches/*
- name: Run 'rm -rf ~/Library/Caches/*'
  ansible.builtin.file:
    path: '~/Library/Caches/'
    state: absent
  become: true
  tags: maintenance

- name: Run 'yarn cache clean'
  ansible.builtin.command: yarn cache clean
  tags: maintenance

- name: Clear print queue
  ansible.builtin.command: cancel -a -
  tags: maintenance
