---
brew_taps:
  - heroku/brew
  - homebrew/bundle
  - homebrew/services
  - microsoft/git

brew_packages:
  - ansible
  - autoconf
  - automake
  - awscli
  - bash
  - binutils
  - cmake
  - coreutils
  - diffutils
  - duf
  - duti
  - exiftool
  - git
  - gmp # rbenv/ruby requirement
  - gnupg
  - gzip
  - heroku/brew/heroku
  - htop
  - jq
  - less
  - libffi
  - libpq # postgres requirement
  - libyaml # rbenv/ruby requirement
  - lotyp/formulae/dockutil
  - mas
  - nano
  - nmap
  - node
  - nvm
  - openssh
  - openssl@3 # rbenv/ruby requirement
  - pre-commit
  - pyenv
  - python@3.9
  - readline # rbenv/ruby requirement
  - rbenv
  - rsync
  # Don't install ruby from homebrew
  # We will use rbenv for this
  # - ruby
  - ruby-build
  - shellcheck
  - stripe/stripe-cli/stripe
  - tidy-html5
  - tree
  - unbound
  - wget
  - wifi-password
  - yq
  - zlib
  - zsh

brew_cask_packages:
  - 1password
  - arq
  - authy
  - chromedriver
  - cyberduck
  - docker
  - dupeguru
  - element
  - fawkes
  - firefox
  - fujitsu-scansnap-home
  - git-credential-manager-core
  - github
  - google-chrome
  - hazel
  - iterm2
  - kindle
  - little-snitch
  - maccy
  - macfuse
  - maestral
  - microsoft-auto-update
  - microsoft-office
  - microsoft-remote-desktop
  - microsoft-teams
  - netnewswire
  - ngrok
  - obsidian
  - omnifocus
  - scrivener
  - signal
  - simple-comic
  - skype
  - slack
  - spotify
  - sublime-text
  - superduper
  - tabula
  - teamviewer
  - the-unarchiver
  - thunderbird
  - timing
  - transmission
  - veracrypt
  - virtualbox
  - visual-studio-code
  - vlc
  - xmind
  - zoom

brew_cask_ql_packages:
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - qlvideo
  - quicklook-csv
  - quicklook-json
  - suspicious-package
  - webpquicklook
