---
# Make sure you do not clash with a brew cask here!
# Get the list of currently installed with 'mas list'.
mas_installed_apps:
  - {id: 1055511498, name: "Day One"}
  - {id: 604802021, name: "Outline"}
  - {id: 1303222628, name: "Paprika Recipe Manager 3"}
  - {id: 1351639930, name: "Gifski"}
  - {id: 1274495053, name: "Microsoft To Do"}

mas_uninstalled_apps:
  - {id: 408981434, name: "iMovie"}
  - {id: 409183694, name: "Keynote"}
  - {id: 409201541, name: "Pages"}
  - {id: 409203825, name: "Numbers"}
  - {id: 682658836, name: "GarageBand"}
